# MongoDB
spring.data.mongodb.uri=${MONGO_URI}

# Mail
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${MAIL_FROM}

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# App URL
app.base.url=${BASE_URL}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_KEY}
cloudinary.api-secret=${CLOUDINARY_SECRET}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=604800000

# Razorpay
razorpay.key.id=${RAZORPAY_KEY}
razorpay.key.secret=${RAZORPAY_SECRET}